name: Coder Education
on: [push]

jobs:
    deploy:
        runs-on: window-latest
        steps:
            - uses: actions/checkout@v2
            
            - run: echo "Setting up NodeJs"
            - name: Setup NodeJs
              uses: actions/setup-node@v1
              with:
               node-version: 12.x

            - run: npm install -g surge
            - run: echo "Deploying website"
            - run: surge ./https://coder-education.surge.sh --token ${{ secrets.SURGE_TOKEN }} 
          
            - run: echo "Please visit => ${{ secrets.SURGE_DOMAIN }}"

  
